name: Validate posts

on:
  push:
    branches: [default]

jobs:
  build:
    name: Validate posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        run: echo "yarn_cache_dir=$(yarn config get cacheFolder)" >> $GITHUB_ENV
      - name: Cache Deps
        uses: actions/cache@v2
        with:
          path: ${{ env.yarn_cache_dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install Dependencies
        run: |
          cd actions-scripts
          yarn install
      - name: Validate posts
        run: |
          cd actions-scripts
          yarn build
          yarn start
      - name: Add and commit
        uses: EndBug/add-and-commit@v9
        with:
          commit: --signoff
          default_author: github_actions
          fetch: false
          tag_push: "--force"
